---

- include: setup-debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: setup-redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon'

- name: Retrieve the number of cores that are available for compilation
  command: nproc
  register: cores

- name: Download the Ruby source code
  get_url: url={{ ruby_download_location }}
           dest=/usr/local/src/
           sha256sum={{ ruby_checksum }}


- name: Extract Ruby source code
  command: tar xvfz {{ ruby_source_location }}/{{ ruby_version }}.tar.gz
  args:
    chdir: "{{ ruby_source_location }}"
    creates: "{{ ruby_source_location }}/{{ ruby_version }}"


- name: Configure Ruby
  command: ./configure --enable-shared --prefix={{ ruby_location }} --disable-install-doc
  args:
    chdir: "{{ ruby_source_location }}/{{ ruby_version }}"
    creates: "{{ ruby_source_location }}/{{ ruby_version }}/Makefile"


- name: Compile Ruby
  command: make --jobs {{ cores.stdout }}
  args:
    chdir: "{{ ruby_source_location }}/{{ ruby_version }}"
    creates: "{{ ruby_source_location }}/{{ ruby_version }}/ruby"

- name: Install Ruby
  command: make install
  args:
    chdir: "{{ ruby_source_location }}/{{ ruby_version }}"
    creates: "{{ ruby_location }}/bin/ruby"

- name: Generate the script that allows you to easily run Rake tasks with the correct RAILS_ENV environment variable, and the wrapper script that contains GC settings
  template: src={{ item }}.j2
            dest=/usr/local/bin/{{ item }}
            owner=root
            group=root
            mode=755
  with_items:
    - rake-env
    - ruby-gc-wrapper

- name: Install Bundler
  command: "{{ ruby_location }}/bin/gem install bundler {{ ruby_bundler_flags }}
            creates={{ ruby_location }}/bin/bundle"

- name: Make Ruby symlinks
  file: path=/usr/local/bin/{{ item }}
        src={{ ruby_location }}/bin/{{ item }}
        state=link
        force=true
  with_items: ruby_symlinks
